---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 西.
--- DateTime: 2022/6/19 23:51
---
local chaid=0

--------------------------查看物品id
function shiyong(e)
    if chaid==0 then return
    end
    local id1=e.itemid
    local s=e.eventobjid
    Chat:sendSystemMsg("物品："..id1,s)
    --if id1==11559 then
    --    Player:removeBackpackItem(s,11559,64)
    --end
end

--------------------------聊天输入id获得物品，开关查看id的功能
function ml(e)
    local nr=e.content
    local wj=e.eventobjid
    if nr=="开启id" then
        chaid=1
    end
    if nr=="关闭id" then
        chaid=0
    end
    local dm=tonumber(nr)
    Player:gainItems(wj,dm,2,1)
end

------------------------- 获取方块坐标、数据

function dianji(e)
    local s=e.eventobjid
    local id1=e.blockid
    Chat:sendSystemMsg("方块id："..id1,s)
    Chat:sendSystemMsg("坐标x："..e.x,s)
    Chat:sendSystemMsg("坐标z："..e.z,s)
    Chat:sendSystemMsg("坐标y："..e.y,s)

    local result,data=Block:getBlockData(e.x,e.y,e.z)
    Chat:sendSystemMsg("当前数据："..data,s)
end

------------------------- 吃面条飞天

function xiaohao(e)
    if e.itemid==12550 then
        Player:changPlayerMoveType(e.eventobjid, 1) --飞天
    end
end



ScriptSupportEvent:registerEvent('Player.UseItem', shiyong) --玩家使用道具
ScriptSupportEvent:registerEvent('Player.SelectShortcut', shiyong) --玩家切换快捷栏
ScriptSupportEvent:registerEvent('Player.NewInputContent',ml)   --玩家发送聊天信息

ScriptSupportEvent:registerEvent('Player.ClickBlock',dianji) --玩家点击方块
ScriptSupportEvent:registerEvent('Player.ConsumeItem',xiaohao) --玩家消耗物品